output_dir='/home/azad/PopCoGenomeS/src/PopCoGenomeS_part_1/output'  #this is the folder where you want your outputs to be 
project_dir_1='/home/azad/PopCoGenomeS/src/PopCoGenomeS_part_1/proc'	#where is your project workspace
basename='example'   #this should be the same as the previous basename in the first part of PopCoGenomeS
genome_source='/home/azad/PopCoGenomeS/example_genomes' #the folder where your genomes are in
genome_ext='.fa' #can be .fna.gz, .fna, .fasta, .fasta.gz
pop_infile_source='/home/azad/PopCoGenomeS/src/PopCoGenomeS_part_1/output'  #where are your genome lists for each vertically-inherited cluster identified in Part 1
path_to_phybreak='/home/azad/PopCoGenomeS/src/PopCoGenomeS_part_2' #where is your align_and_construct_trees folder
path_to_PopCoGenomeS='/home/azad/miniconda3/envs/popcogenomes' #path to your conda environment PopCoGenomeS
path_to_PopCoGenomeS_R='/home/azad/miniconda3/envs/popcogenomes_r' #path to your conda environment for PopCoGenomeS_R
